### ISSUE TITLE
GodinHook的源码在哪里找的呢

### ISSUE THREAD

**Issue by smartdone** [xiaobaiyey/dexload#3]
我最近也在玩native层的hook，但是CydiaSubstrate好像不支持arm64的hook，我在32位上的设备试成功了。还有就是GodinHook支持arm64的hook吗？跪求解答一下，谢谢

**Comment by xiaobaiyey** [comment]
64位暂时没测试。

**Comment by sammy698** [comment]
同问，有计划去支持arm64吗？我做了一点64位兼容后，还是没能hook成功~~。
方便的话，可以私聊我。qq：529231698

**Comment by genglei-cuan** [comment]
我是 godinhook 的原作者，对64位ARM指令集，没有实际开发经验，所以没做这方面的支持。32位，已经挺稳定了。
